version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
         name: Enabling QEMU
         command: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run:
         name: Build
         command: |
           SCRIPT="apt update \
                   && apt install -y --no-install-recommends build-essential libglib2.0-dev pkg-config cmake debhelper \
                   && dpkg-buildpackage -b"
           pwd
           docker run -t --rm -v ${PWD}:/src -w /src \
               multiarch/ubuntu-core:x86_64-xenial \
               bash -c "$SCRIPT"
